os: linux
language: java
jdk:
  - openjdk11
services:
  - docker
env:
  global:
    - GIT_SHA=$(git rev-parse HEAD)
cache:
  directories:
    - $HOME/.m2
before_install:
  - docker pull openjdk:11
  - chmod +x ./travis-build.sh
  - chmod +x ./travis-deploy.sh
script:
  - ./travis-build.sh
after_success:
  - ./travis-deploy.sh