apiVersion: skaffold/v2beta12
kind: Config
metadata:
  name: questboard
build:
  artifacts:
  - image: demo-spring-rx
    context: demo.spring.rx
    docker:
      dockerfile: Dockerfile
  - image: user-service-image
    context: user.service
    docker:
      dockerfile: Dockerfile
  - image: chat-service-image
    context: ChatWebSocket
    docker:
      dockerfile: Dockerfile
  - image: review-service-image
    context: review.service
    docker:
      dockerfile: Dockerfile
  - image: quest-service-image
    context: quest.service
    docker:
      dockerfile: Dockerfile
  - image: reward-service-image
    context: reward.service
    docker:
      dockerfile: Dockerfile
deploy:
  kubectl:
    manifests:
    - demo.spring.rx/deployment.yaml
    - user.service/user.deployment.yaml
    - ChatWebSocket/deployment.yaml
    - quest.service/quest.deployment.yaml
    - review.service/review.deployment.yaml
    - reward.service/reward.deployment.yaml
    - redis-deployment.yaml
portForward:
- resourceType: service
  resourceName: demo-spring-rx
  port: 8082
- resourceType: service
  resourceName: user.service
  port: 8083
- resourceType: service
  resourceName: chat.service
  port: 8084
- resourceType: service
  resourceName: review.service
  port: 8085
- resourceType: service
  resourceName: quest.service
  port: 8088
- resourceType: service
  resourceName: reward.service
  port: 8089