apiVersion: v1
kind: Service
metadata:
  name: user-svc
  labels:
    app: user-svc
spec:
  type: NodePort
  ports:
    - port: 8083
      targetPort: 8083
      nodePort: 30002
  selector:
    app: user-deployment
---
kind: Service
apiVersion: v1
metadata:
  name: mysql-userdb
spec:
  ports:
    - port: 3306
      targetPort: 3306
      protocol: TCP
---
kind: Endpoints
apiVersion: v1
metadata:
  name: mysql-userdb
subsets:
  - addresses:
      - ip: 192.168.49.1
    ports:
      -  port: 3308
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-deployment
  labels:
    app: user-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-deployment
  template:
    metadata:
      labels:
        app: user-deployment
    spec:
      containers:
        - name: user-deployment
          image: user-service-image
          ports:
          - containerPort: 8083
            protocol: TCP
          env:
            - name: USERSVC_DB_HOST
              valueFrom:
                secretKeyRef:
                  name: usersvc-db-secret
                  key: usersvc_db_host
            - name: USERSVC_DB_PORT
              valueFrom:
                secretKeyRef:
                  name: usersvc-db-secret
                  key: usersvc_db_port
            - name: USERSVC_DB_USER
              valueFrom:
                secretKeyRef:
                  name: usersvc-db-secret
                  key: usersvc_db_user
            - name: USERSVC_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: usersvc-db-secret
                  key: usersvc_db_password
            - name: USERSVC_DB_DATABASE
              valueFrom:
                secretKeyRef:
                  name: usersvc-db-secret
                  key: usersvc_db_database