apiVersion: v1
kind: Service
metadata:
  name: user-svc
  labels:
    app: user-svc
spec:
  type: NodePort
  ports:
    - port: 8083
      targetPort: 8083
      nodePort: 30002
  selector:
    app: user-svc
---
kind: Service
apiVersion: v1
metadata:
  name: mysql-userdb
spec:
  ports:
    - port: 3306
      targetPort: 3306
      protocol: TCP
---
kind: Endpoints
apiVersion: v1
metadata:
  name: mysql-userdb
subsets:
  - addresses:
      - ip: 192.168.49.1
    ports:
      -  port: 3307