apiVersion: v1
kind: Service
metadata:
  name: demo-spring-rx
  labels:
    app: demo-spring-rx
spec:
  type: NodePort
  ports:
    - port: 8082
      targetPort: 8082
      //nodeport means expose to outside
      nodePort: 30001 
  selector:
    app: demo-spring-rx
---
kind: Service
apiVersion: v1
metadata:
  name: mariadb-tododb
spec:
  ports:
    - port: 3306
      targetPort: 3306
      protocol: TCP
---
kind: Endpoints
apiVersion: v1
metadata:
  name: mariadb-tododb
subsets:
  - addresses:
    - ip: 192.168.49.1 //this need to start minikube and get the minikube IP , this is the local server
    ports:
    -  port: 3307
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-spring-rx
  labels:
    app: demo-spring-rx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo-spring-rx
  template:
    metadata:
      labels:
        app: demo-spring-rx
    spec:
      containers:
      - name: demo-spring-rx
        image: demo-spring-rx
        ports:
        - containerPort: 8082
          protocol: TCP
