apiVersion: v1
kind: Service
metadata:
  name: review-svc
  labels:
    app: review-svc
spec:
  type: NodePort
  ports:
    - port: 8085
      targetPort: 8085
      nodePort: 30004
  selector:
    app: review-deployment
---
kind: Service
apiVersion: v1
metadata:
  name: mysql-reviewdb
spec:
  ports:
    - port: 3306
      targetPort: 3306
      protocol: TCP
---
kind: Endpoints
apiVersion: v1
metadata:
  name: mysql-review-endpoint
subsets:
  - addresses:
      - ip: 192.168.49.1
    ports:
      -  port: 3306
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: review-deployment
  labels:
    app: review-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: review-deployment
  template:
    metadata:
      labels:
        app: review-deployment
    spec:
      containers:
        - name: review-deployment
          image: review-service-image
          ports:
            - containerPort: 8085
              protocol: TCP
          env:
            - name: REVIEWSVC_DB_HOST
              valueFrom:
                secretKeyRef:
                  name: reviewsvc-db-secret
                  key: reviewsvc_db_host
            - name: REVIEWSVC_DB_PORT
              valueFrom:
                secretKeyRef:
                  name: reviewsvc-db-secret
                  key: reviewsvc_db_port
            - name: REVIEWSVC_DB_USER
              valueFrom:
                secretKeyRef:
                  name: reviewsvc-db-secret
                  key: reviewsvc_db_user
            - name: REVIEWSVC_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: reviewsvc-db-secret
                  key: reviewsvc_db_password
            - name: REVIEWSVC_DB_DATABASE
              valueFrom:
                secretKeyRef:
                  name: reviewsvc-db-secret
                  key: reviewsvc_db_database
            - name: OAUTH2SERVER_JWKURI
              valueFrom:
                secretKeyRef:
                  name: reviewsvc-db-secret
                  key: oauth2server_jwkuri