apiVersion: v1
kind: Service
metadata:
  name: quest-svc
  labels:
    app: quest-svc
spec:
  type: NodePort
  ports:
    - port: 8085
      targetPort: 8085
      nodePort: 30005
  selector:
    app: quest-deployment
---
kind: Service
apiVersion: v1
metadata:
  name: mysql-questdb
spec:
  ports:
    - port: 3306
      targetPort: 3306
      protocol: TCP
---
kind: Endpoints
apiVersion: v1
metadata:
  name: mysql-questdb
subsets:
  - addresses:
      - ip: 192.168.49.1
    ports:
      -  port: 3310
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: quest-deployment
  labels:
    app: quest-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: quest-deployment
  template:
    metadata:
      labels:
        app: quest-deployment
    spec:
      containers:
        - name: quest-deployment
          image: quest-service-image
          ports:
            - containerPort: 8085
              protocol: TCP
